# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

src_affgaussian <- function(X, use_auto, bandwidth) {
    .Call('_dglearn_src_affgaussian', PACKAGE = 'dglearn', X, use_auto, bandwidth)
}

src_dsm_dist2diff <- function(Px, Py) {
    .Call('_dglearn_src_dsm_dist2diff', PACKAGE = 'dglearn', Px, Py)
}

src_dsm_spheremean <- function(data, weight, maxiter, abstol) {
    .Call('_dglearn_src_dsm_spheremean', PACKAGE = 'dglearn', data, weight, maxiter, abstol)
}

