# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('_dglearn_rcpparma_hello_world', PACKAGE = 'dglearn')
}

rcpparma_outerproduct <- function(x) {
    .Call('_dglearn_rcpparma_outerproduct', PACKAGE = 'dglearn', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_dglearn_rcpparma_innerproduct', PACKAGE = 'dglearn', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_dglearn_rcpparma_bothproducts', PACKAGE = 'dglearn', x)
}

src_dsm_dist2diff <- function(Px, Py) {
    .Call('_dglearn_src_dsm_dist2diff', PACKAGE = 'dglearn', Px, Py)
}

src_dsm_spheremean <- function(data, weight, maxiter, abstol) {
    .Call('_dglearn_src_dsm_spheremean', PACKAGE = 'dglearn', data, weight, maxiter, abstol)
}

